import sqlmodel
"""update the model

Revision ID: 0ffb68bcb0f0
Revises: d112552521b8
Create Date: 2024-06-11 13:31:01.414357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffb68bcb0f0'
down_revision: Union[str, None] = 'd112552521b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'data')
    # ### end Alembic commands ###
