import sqlmodel
"""Add is_superuser in table email

Revision ID: 95b9f6ba2def
Revises: 2a95fc35f847
Create Date: 2024-06-10 01:07:47.253235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b9f6ba2def'
down_revision: Union[str, None] = '2a95fc35f847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'is_superuser')
    # ### end Alembic commands ###
