import sqlmodel
"""update the model

Revision ID: d112552521b8
Revises: 339d9bf7a72e
Create Date: 2024-06-11 02:32:20.736228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd112552521b8'
down_revision: Union[str, None] = '339d9bf7a72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('userinfo', sa.Column('cookies', sa.JSON(), nullable=True))
    op.drop_column('userinfo', 'name')
    op.drop_column('userinfo', 'cookie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo', sa.Column('cookie', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('userinfo', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('userinfo', 'cookies')
    op.drop_column('userinfo', 'nickname')
    # ### end Alembic commands ###
